const state={bootstrap:null,currentDeal:null,deal:null,selectedValue:null,pendingReview:null,pendingFinding:null,pendingPurge:null};
const $=selector=>document.querySelector(selector);
const escapeHTML=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,options={}){const request={...options,headers:new Headers(options.headers||{})};if(request.method==='POST'&&state.bootstrap?.user?.csrf_token)request.headers.set('X-CSRF-Token',state.bootstrap.user.csrf_token);const response=await fetch(path,request);const body=await response.json();if(!response.ok){const error=new Error(body.error||'Request failed');error.status=response.status;throw error}return body}
function toast(message){const node=$('#toast');node.textContent=message;node.classList.add('show');setTimeout(()=>node.classList.remove('show'),2800)}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===name));document.querySelectorAll('.nav-item').forEach(v=>v.classList.toggle('active',v.dataset.view===name));if(name!=='pipeline'&&!state.currentDeal){toast('Select a deal first');setView('pipeline')}}
document.querySelectorAll('.nav-item').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
async function load(){state.bootstrap=await api('/api/bootstrap');document.body.classList.add('signed-in');$('#assumption-field').innerHTML=state.bootstrap.manualAssumptionFields.map(field=>`<option value="${escapeHTML(field.name)}">${escapeHTML(field.label)}${field.unit?` (${escapeHTML(field.unit)})`:''}</option>`).join('');renderPipeline();if(!state.currentDeal&&state.bootstrap.deals[0])await selectDeal(state.bootstrap.deals[0].id)}
function renderPipeline(){const deals=state.bootstrap.deals;$('#metric-deals').textContent=deals.length;$('#metric-review').textContent=deals.filter(d=>d.status==='needs_review').length;$('#metric-findings').textContent=deals.reduce((n,d)=>n+d.finding_count,0);$('#metric-approved').textContent=state.deal?state.deal.values.filter(v=>v.review_status==='approved').length:0;const query=$('#deal-search').value.toLowerCase();const filtered=deals.filter(d=>`${d.name} ${d.address}`.toLowerCase().includes(query));$('#deal-list').innerHTML=filtered.length?filtered.map(d=>`<article class="deal-row" tabindex="0" data-id="${d.id}"><div><h3>${escapeHTML(d.name)}</h3><p>${escapeHTML(d.address||'Address not entered')}</p></div><div><span class="badge">${escapeHTML(d.status.replaceAll('_',' '))}</span></div><div><strong>${d.document_count}</strong><small> documents</small></div><div><strong>${d.finding_count}</strong><small> findings</small></div><button class="secondary">Open →</button></article>`).join(''):'<p class="empty">No matching deals.</p>';document.querySelectorAll('.deal-row').forEach(row=>{row.addEventListener('click',()=>selectDeal(row.dataset.id).then(()=>setView('documents')));row.addEventListener('keydown',event=>{if(event.key==='Enter')row.click()})})}
async function selectDeal(id){state.currentDeal=id;state.deal=await api(`/api/deals/${id}`);renderDeal();renderPipeline()}
function renderDeal(){const d=state.deal;$('#documents-subtitle').textContent=`${d.deal.name} · Originals preserved with SHA-256 provenance.`;$('#document-count').textContent=`${d.documents.length} files`;$('#document-list').innerHTML=d.documents.length?d.documents.map(doc=>`<article class="document-card"><div class="file-icon">${doc.detected_mime.includes('pdf')?'PDF':doc.detected_mime.includes('sheet')?'XLSX':doc.detected_mime.includes('csv')?'CSV':'IMG'}</div><h3 title="${escapeHTML(doc.original_name)}">${escapeHTML(doc.original_name)}</h3><span class="badge">${escapeHTML(doc.category.replaceAll('_',' '))}</span><p>${escapeHTML(doc.processing_status.replaceAll('_',' '))} · ${(doc.size_bytes/1024).toFixed(1)} KB</p><p title="${doc.sha256}">SHA-256 ${doc.sha256.slice(0,12)}…</p>${doc.original_purged_at?`<p><strong>Original bytes purged</strong><br>${escapeHTML(doc.original_purged_at.slice(0,19))}</p>`:state.bootstrap.user.role==='admin'?`<button class="secondary purge-original" data-id="${doc.id}" data-name="${escapeHTML(doc.original_name)}">Purge original bytes</button>`:''}</article>`).join(''):'<p class="empty">Upload a fictional OM, rent roll or T-12 to begin.</p>';document.querySelectorAll('.purge-original').forEach(button=>button.addEventListener('click',()=>{state.pendingPurge=button.dataset.id;$('#purge-document-name').textContent=button.dataset.name;$('#purge-reason').value='';$('#purge-password').value='';$('#purge-dialog').showModal()}));renderValues();renderFindings();renderApproved();renderAudit();$('#metric-approved').textContent=d.values.filter(v=>v.review_status==='approved').length}
function renderValues(){const filter=$('#review-filter').value;const values=state.deal.values.filter(v=>filter==='all'||v.review_status===filter);$('#value-list').innerHTML=values.length?values.map(v=>`<article class="value-row ${state.selectedValue?.id===v.id?'selected':''}" data-id="${v.id}" tabindex="0"><div class="value-meta"><label>${escapeHTML(v.field_name.replaceAll('_',' '))}</label><span class="badge">${escapeHTML(v.review_status.replaceAll('_',' '))}</span></div><strong>${escapeHTML(v.normalized_value??v.raw_value)}</strong><span class="confidence ${v.confidence<.6?'low':''}">${Math.round(v.confidence*100)}% confidence · page ${v.page_number??'n/a'}</span><div class="review-actions"><button class="primary approve">Approve</button><button class="secondary edit">Edit</button><button class="secondary reject">Reject</button></div></article>`).join(''):'<p class="empty">No values in this state.</p>';document.querySelectorAll('.value-row').forEach(row=>{const value=state.deal.values.find(v=>v.id===row.dataset.id);row.addEventListener('click',()=>selectValue(value));row.querySelector('.approve').addEventListener('click',event=>{event.stopPropagation();openReview(value,'approved')});row.querySelector('.reject').addEventListener('click',event=>{event.stopPropagation();openReview(value,'rejected')});row.querySelector('.edit').addEventListener('click',event=>{event.stopPropagation();openReview(value,'approved')});row.addEventListener('keydown',event=>{if(event.key==='Enter')selectValue(value)})})}
function selectValue(value){state.selectedValue=value;renderValues();const doc=state.deal.documents.find(d=>d.id===value.document_id);$('#source-page').textContent=value.source_kind==='user_entered'?'User-entered assumption':`${doc?.original_name||'Source'} · page ${value.page_number||'n/a'}`;const viewer=$('#source-viewer');const box=value.bbox;const highlight=box?`<span class="source-highlight" aria-label="Extracted source area" style="left:${box[0]*100}%;top:${box[1]*100}%;width:${box[2]*100}%;height:${box[3]*100}%"></span>`:'';if(doc?.detected_mime==='application/pdf'&&value.page_number){viewer.innerHTML=`<div class="page-image"><img alt="Source page ${value.page_number}" src="/api/documents/${doc.id}/page/${value.page_number}">${highlight}</div>`}else if(doc&&['image/png','image/jpeg'].includes(doc.detected_mime)){viewer.innerHTML=`<div class="page-image"><img alt="Source document" src="/api/documents/${doc.id}">${highlight}</div>`}else{viewer.innerHTML=`<div class="source-card"><p><strong>${value.source_kind==='user_entered'?'Recorded rationale':'Exact source excerpt'}</strong></p><p><mark>${escapeHTML(value.source_excerpt)}</mark></p><p>Source-text hash<br><code>${escapeHTML(value.source_text_hash)}</code></p><p>Bounding box: ${escapeHTML(JSON.stringify(value.bbox)||'not available')}</p></div>`}}
function openReview(value,status){state.pendingReview={value,status};$('#review-dialog-title').textContent=status==='rejected'?'Reject value':'Approve or edit value';$('#review-normalized').value=value.normalized_value??value.raw_value;$('#review-normalized').required=status==='approved';$('#review-comments').value='';$('#review-comments').required=status==='rejected';$('#review-dialog').showModal()}
function renderFindings(){const findings=state.deal.findings;$('#finding-list').innerHTML=findings.length?findings.map(f=>`<article class="finding ${f.severity}"><span class="severity">${escapeHTML(f.severity)}</span><div><h3>${escapeHTML(f.rule_code.replaceAll('_',' '))}</h3><p>${escapeHTML(f.explanation)}</p><p><strong>Next:</strong> ${escapeHTML(f.suggested_next_step)}</p></div><div>${f.resolution_status==='open'?`<button class="secondary resolve" data-id="${f.id}">Resolve</button>`:`<span class="badge">${escapeHTML(f.resolution_status)}</span>`}</div></article>`).join(''):'<div class="empty-state"><h2>No findings generated</h2><p>Run checks after documents have produced extracted values.</p></div>';document.querySelectorAll('.resolve').forEach(button=>button.addEventListener('click',()=>{state.pendingFinding=button.dataset.id;$('#resolution-notes').value='';$('#resolution-dialog').showModal()}))}
function renderApproved(){const values=state.deal.values.filter(v=>v.review_status==='approved');$('#approved-list').innerHTML=values.length?`<table class="data-table"><thead><tr><th>Field</th><th>Approved value</th><th>Source</th><th>Reviewed</th></tr></thead><tbody>${values.map(v=>{const doc=state.deal.documents.find(d=>d.id===v.document_id);const source=v.source_kind==='user_entered'?`User-entered · ${escapeHTML(v.rationale)}`:`${escapeHTML(doc?.original_name)} · p.${v.page_number??'—'}`;return`<tr><td>${escapeHTML(v.field_name)}</td><td><strong>${escapeHTML(v.normalized_value)}</strong></td><td>${source}</td><td>${escapeHTML(v.reviewed_at?.slice(0,16)||'—')}</td></tr>`}).join('')}</tbody></table>`:'<p class="empty">No approved facts yet.</p>'}
function renderJurisdiction(result){
  const target=$('#jurisdiction-content');
  if(!['matched','state_only'].includes(result.status)){
    target.innerHTML=`<div class="empty-state"><span>⌖</span><h2>${escapeHTML(result.status.replaceAll('_',' '))}</h2><p>${escapeHTML(result.message||'No researched local context matched this approved county FIPS.')}</p><p>Coverage: ${escapeHTML(result.coverage)} · network requests: ${escapeHTML(result.networkRequests)}</p></div>`;
    return;
  }
  const data=result.results,policy=data.policy,state=data.stateRegulation,fresh=result.snapshot.freshness,facilities=data.facilities;
  const citations=[...(policy?.citations||[]),...(data.politicalRisk?.citations||[]),...(state?.citations||[])];
  target.innerHTML=`<div class="jurisdiction-grid"><article class="jurisdiction-card jurisdiction-wide"><span class="badge">${escapeHTML(result.status.replaceAll('_',' '))} · ${escapeHTML(result.coverage)}</span><h2>${escapeHTML(policy?.name||state?.name||`FIPS ${data.countyFips}`)}</h2><p>Verified: ${result.verified?'yes':'no'} · snapshot ${escapeHTML(fresh.status)} · as of ${escapeHTML(fresh.asOf||'unknown')} · ${escapeHTML(fresh.ageDays??'unknown')} days old · automatic network requests: ${escapeHTML(result.networkRequests)}</p></article><article class="jurisdiction-card"><h3>County policy</h3><p><strong>${escapeHTML(policy?.title||'No county policy record')}</strong></p><p>${escapeHTML(policy?.description||'Only broader/local auxiliary context is available.')}</p><p>Status ${escapeHTML(policy?.status||'unknown')} · level ${escapeHTML(policy?.level??'unknown')} · reviewed ${escapeHTML(policy?.last_reviewed||'unknown')}</p></article><article class="jurisdiction-card"><h3>Risk and resources</h3><p>Political risk: ${escapeHTML(data.politicalRisk?.score_label||'not covered')}</p><p>Water stress: ${escapeHTML(data.waterStress?.label||'not covered')} ${data.waterStress?'(approximate)':''}</p><p>Water data date: ${escapeHTML(result.snapshot.datasetDates.waterStress||'unknown')}</p></article><article class="jurisdiction-card"><h3>Facilities and incentives</h3><p>${facilities?`${escapeHTML(facilities.count)} facilities · ${escapeHTML(facilities.operationalCount)} operational · ${escapeHTML(facilities.knownCapacityMw)} MW known capacity`:'No facility records'}</p><p>${escapeHTML(data.taxIncentives.length)} matching incentive program(s); verify current eligibility with officials.</p></article><article class="jurisdiction-card"><h3>State context</h3><p><strong>${escapeHTML(state?.name||'Not covered')}</strong></p><p>${escapeHTML(state?.summary||'No state record in this snapshot.')}</p></article><article class="jurisdiction-card jurisdiction-wide"><h3>Source citations (not fetched)</h3>${citations.length?`<ul>${citations.map(item=>`<li>${escapeHTML(item.label)}<br><span class="citation-url">${escapeHTML(item.url)}</span></li>`).join('')}</ul>`:'<p>No URL citations in matched records.</p>'}<p><strong>Upstream limitations:</strong> ${escapeHTML((result.limitations||[]).join(' '))}</p></article></div>`;
}
function renderAudit(){$('#audit-list').innerHTML=state.deal.audit.length?state.deal.audit.map(e=>`<article class="event"><h3>${escapeHTML(e.action.replaceAll('.',' · '))}</h3><p>${escapeHTML(e.entity_type)} · ${escapeHTML(e.created_at.slice(0,19))}</p><code>${escapeHTML(e.event_hash.slice(0,20))}…</code></article>`).join(''):'<p class="empty">No events.</p>'}
$('#deal-search').addEventListener('input',renderPipeline);$('#review-filter').addEventListener('change',renderValues);$('#new-deal').addEventListener('click',()=>$('#new-deal-dialog').showModal());$('#create-deal').addEventListener('click',async event=>{event.preventDefault();const form=$('#new-deal-form');if(!form.reportValidity())return;const payload=Object.fromEntries(new FormData(form));const deal=await api('/api/deals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#new-deal-dialog').close();state.bootstrap=await api('/api/bootstrap');await selectDeal(deal.id);setView('documents');toast('Fictional deal created')});
$('#new-assumption').addEventListener('click',()=>$('#assumption-dialog').showModal());$('#create-assumption').addEventListener('click',async event=>{event.preventDefault();const form=$('#assumption-form');if(!form.reportValidity())return;const payload=Object.fromEntries(new FormData(form));await api(`/api/deals/${state.currentDeal}/assumptions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#assumption-dialog').close();form.reset();await selectDeal(state.currentDeal);setView('review');toast('Assumption submitted for review')});
$('#submit-purge').addEventListener('click',async event=>{event.preventDefault();const form=$('#purge-form');if(!form.reportValidity()||!state.pendingPurge)return;await api(`/api/documents/${state.pendingPurge}/purge-original`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:$('#purge-reason').value,current_password:$('#purge-password').value})});$('#purge-password').value='';$('#purge-dialog').close();state.pendingPurge=null;toast('Original document bytes purged');await selectDeal(state.currentDeal)});
$('#submit-review').addEventListener('click',async event=>{event.preventDefault();const form=$('#review-form');if(!form.reportValidity()||!state.pendingReview)return;const {value,status}=state.pendingReview;const resource=value.entity_type==='manual_assumption'?'assumptions':'values';await api(`/api/${resource}/${value.id}/review`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,normalized_value:$('#review-normalized').value,comments:$('#review-comments').value})});$('#review-dialog').close();state.pendingReview=null;toast(`Value ${status}`);await selectDeal(state.currentDeal)});$('#submit-resolution').addEventListener('click',async event=>{event.preventDefault();const form=$('#resolution-form');if(!form.reportValidity()||!state.pendingFinding)return;await api(`/api/findings/${state.pendingFinding}/resolve`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({notes:$('#resolution-notes').value})});$('#resolution-dialog').close();state.pendingFinding=null;toast('Finding resolved');await selectDeal(state.currentDeal)});
$('#upload').addEventListener('change',async event=>{for(const file of event.target.files){try{toast(`Processing ${file.name} locally…`);await api(`/api/deals/${state.currentDeal}/upload`,{method:'POST',headers:{'X-Filename':file.name},body:file})}catch(error){toast(error.message)}}await selectDeal(state.currentDeal);event.target.value=''});
$('#run-reconcile').addEventListener('click',async()=>{const results=await api(`/api/deals/${state.currentDeal}/reconcile`,{method:'POST'});toast(`${results.length} discrepancies found`);await selectDeal(state.currentDeal)});
async function generate(kind){const result=await api(`/api/deals/${state.currentDeal}/export/${kind}`,{method:'POST'});$('#export-preview').textContent=JSON.stringify(result,null,2);return result}
$('#export-test2').addEventListener('click',()=>generate('test2'));$('#export-memo').addEventListener('click',()=>generate('memo'));$('#test1-status').addEventListener('click',async()=>{const result=await api(`/api/deals/${state.currentDeal}/export/test1`,{method:'POST'});renderJurisdiction(result);toast(`Local context: ${result.status.replaceAll('_',' ')}`)});$('#memo-generate').addEventListener('click',async()=>{const memo=await generate('memo');$('#memo-content').innerHTML=`<p class="watermark">DRAFT · NOT INVESTMENT OR LEGAL ADVICE</p><h2>${escapeHTML(memo.title)}</h2><p>${escapeHTML(memo.executiveSummary)}</p><h2>Approved facts</h2><ul>${memo.approvedFacts.map(f=>`<li>${escapeHTML(f.statement)} <small>[${f.source.sourceType==='user_entered'?'user-entered assumption':`document ${escapeHTML(f.source.documentId?.slice(0,8)||'unknown')}, page ${f.source.page??'n/a'}`}]</small></li>`).join('')}</ul><h2>Key discrepancies</h2><ul>${memo.keyDiscrepancies.map(f=>`<li>${escapeHTML(f.explanation)}</li>`).join('')}</ul>`;setView('memo')});
$('#signin-form').addEventListener('submit',async event=>{event.preventDefault();try{const payload=Object.fromEntries(new FormData(event.currentTarget));await api('/api/signin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});await load();toast('Signed in to local workspace')}catch(error){toast(error.message)}});
$('#signout').addEventListener('click',async()=>{await api('/api/signout',{method:'POST'});state.bootstrap=null;state.currentDeal=null;state.deal=null;document.body.classList.remove('signed-in');$('#signin-form input[name="password"]').value='';$('#signin-form input[name="email"]').focus()});
load().catch(error=>{if(error.status!==401){console.error(error);toast(error.message)}});
