const OPPORTUNITY_DIMENSIONS=['rent','basis','noi','cap_rate','vacancy','comparables','location'];
const OPPORTUNITY_TIERS={HIGH_PRIORITY_REVIEW:'High-priority review',WORTH_REVIEWING:'Worth reviewing',LOW_PRIORITY:'Low priority',INSUFFICIENT_EVIDENCE:'Insufficient evidence'};
const OPPORTUNITY_CURRENCY={CURRENT:'Current',OUTDATED_EVIDENCE:'New evidence — rescreen',NOT_SCREENED:'Not screened'};
let opportunitySearchTimer=null,opportunityDialogOpener=null;

function opportunityState(){
  if(!state.opportunityFinder){
    const finder={items:[],summary:{},page:0,limit:25,total:0,detail:null,filters:{status:'candidate',sort:'screening_tier',direction:'asc'}};
    if(location.hash.startsWith('#opportunity-finder?')){
      const params=new URLSearchParams(location.hash.split('?',2)[1]),allowed=['q','market','property_type','screening_tier','screening_currency_status','status','evidence_completeness_min','freshness_max_days','rent_gap_min','basis_discount_min','sort','direction'];
      allowed.forEach(key=>{if(params.has(key))finder.filters[key]=params.get(key)});const limit=Number(params.get('limit'));if([25,50,100].includes(limit))finder.limit=limit;const offset=Number(params.get('offset'));if(Number.isInteger(offset)&&offset>=0)finder.page=Math.floor(offset/finder.limit);finder.pendingCandidate=params.get('candidate');
      requestAnimationFrame(()=>{for(const[key,value]of Object.entries(finder.filters)){const control=document.querySelector(`#opportunity-filters [name="${CSS.escape(key)}"]`);if(control)control.value=value}$('#opportunity-page-size').value=String(finder.limit)});
    }
    state.opportunityFinder=finder;
  }
  return state.opportunityFinder;
}
function canManageOpportunities(){return ['analyst','admin'].includes(state.bootstrap?.user?.role)}
function displayValue(value){return value===null||value===undefined||value===''?'—':String(value)}
function exactPercent(value,places=1){
  if(value===null||value===undefined||value==='')return null;
  const match=String(value).trim().match(/^([+-]?)(\d+)(?:\.(\d+))?$/);if(!match)return null;
  const negative=match[1]==='-',fraction=match[3]||'',digits=BigInt(`${match[2]}${fraction}`),power=fraction.length-2-places;
  let scaled;if(power>0){const divisor=10n**BigInt(power),quotient=digits/divisor,remainder=digits%divisor;scaled=quotient+(remainder*2n>=divisor?1n:0n)}else scaled=digits*(10n**BigInt(-power));
  const padded=scaled.toString().padStart(places+1,'0'),rendered=(places?`${padded.slice(0,-places)}.${padded.slice(-places)}`:padded).replace(/\.0+$/,'').replace(/(\.\d*?)0+$/,'$1');return`${negative&&scaled!==0n?'-':''}${rendered}`;
}
function formatOpportunityPercent(value){const percent=exactPercent(value);return percent===null?'—':`${percent}%`}
function formatGap(value,kind){const percent=exactPercent(value);if(percent===null)return'—';const negative=percent.startsWith('-'),magnitude=negative?percent.slice(1):percent;return`${magnitude}% ${negative?'above':'below'} ${kind}`}
function formatOpportunityMoney(value,unit,totalBasis=false){
  if(value===null||value===undefined||value==='')return'—';const raw=String(value).trim(),match=raw.match(/^([+-]?)(\d+)(?:\.(\d+))?$/);
  if(!match)return`${escapeHTML(raw)}${unit?` ${escapeHTML(unit)}`:''}`;
  const grouped=match[2].replace(/\B(?=(\d{3})+(?!\d))/g,','),fraction=match[3]?`.${match[3]}`:'',amount=`${match[1]==='-'?'−':''}$${grouped}${fraction}`;
  const suffix=unit==='USD/unit'?'/unit':unit==='USD/SF'?'/SF':unit&&unit!=='USD'?` ${escapeHTML(unit)}`:'';return`${amount}${suffix}${totalBasis&&unit==='USD'?' total basis':''}`;
}
function opportunityTierBadge(tier){return`<span class="opportunity-badge tier-${escapeHTML((tier||'none').toLowerCase().replaceAll('_','-'))}">${escapeHTML(OPPORTUNITY_TIERS[tier]||'Not screened')}</span>`}
function opportunityCurrencyBadge(status){return`<span class="opportunity-badge currency-${escapeHTML((status||'none').toLowerCase().replaceAll('_','-'))}">${escapeHTML(OPPORTUNITY_CURRENCY[status]||status||'Not screened')}</span>`}
function opportunityQuery(){
  const f=opportunityState().filters,params=new URLSearchParams();
  Object.entries(f).forEach(([key,value])=>{if(value!==''&&value!==null&&value!==undefined)params.set(key,String(value))});
  params.set('limit',String(opportunityState().limit));params.set('offset',String(opportunityState().page*opportunityState().limit));return params;
}
function syncOpportunityUrl(candidateId=null){
  const params=opportunityQuery();if(candidateId)params.set('candidate',candidateId);history.replaceState(null,'',`#opportunity-finder?${params}`);
}
async function loadOpportunityFinder(force=false){
  if(!state.bootstrap)return;
  const finder=opportunityState();
  if(finder.loading&&!force)return;
  finder.loading=true;$('#opportunity-list-status').textContent='Loading opportunity candidates';
  try{
    const result=await api(`/api/opportunities?${opportunityQuery()}`);finder.items=result.items;finder.summary=result.summary||{};finder.total=result.pagination.total;finder.loading=false;renderOpportunityFinder();if(finder.pendingCandidate){const candidateId=finder.pendingCandidate;finder.pendingCandidate=null;await openOpportunityDetail(candidateId)}else syncOpportunityUrl(finder.detail?.candidate?.id||null);
  }catch(error){finder.loading=false;$('#opportunity-list-status').textContent=`Unable to load candidates: ${error.message}`;throw error}
}
function renderOpportunitySummary(){
  const s=opportunityState().summary;$('#opportunity-total').textContent=formatCount(s.total_candidates);$('#opportunity-high').textContent=formatCount(s.high_priority_review);$('#opportunity-worth').textContent=formatCount(s.worth_reviewing);$('#opportunity-needs').textContent=formatCount(s.needs_evidence);$('#opportunity-stale').textContent=formatCount(s.stale_screening);
}
function opportunityRow(item){
  const property=item.display_name||item.address||'Unnamed candidate',market=[item.market,item.submarket].filter(Boolean).join(' · ')||'Market not supplied',current=item.screening_currency_status==='CURRENT';
  return`<tr><td><strong>${escapeHTML(property)}</strong><small>${escapeHTML(item.address||'Address not supplied')}</small></td><td>${escapeHTML(market)}</td><td>${escapeHTML(item.property_type.replaceAll('_',' '))}</td><td>${formatOpportunityMoney(item.acquisition_basis,item.basis_unit,true)}</td><td>${escapeHTML(formatGap(current?item.rent_gap_pct:null,'market'))}</td><td>${formatOpportunityMoney(current?item.evidence_supported_noi_delta:null,'USD')}</td><td>${escapeHTML(formatOpportunityPercent(current?item.evidence_completeness:null))}</td><td>${current&&item.evidence_freshness_days!==null?`${escapeHTML(item.evidence_freshness_days)} days`:'—'}</td><td>${opportunityTierBadge(item.screening_tier)}</td><td>${opportunityCurrencyBadge(item.screening_currency_status)}</td><td><button class="secondary opportunity-open" data-id="${escapeHTML(item.id)}" type="button" aria-label="Open ${escapeHTML(property)}">Open →</button></td></tr>`;
}
function opportunityCard(item){
  const property=item.display_name||item.address||'Unnamed candidate',current=item.screening_currency_status==='CURRENT';
  return`<article class="opportunity-card"><div><h2>${escapeHTML(property)}</h2><p>${escapeHTML(item.address||'Address not supplied')}<br>${escapeHTML([item.market,item.submarket].filter(Boolean).join(' · ')||'Market not supplied')}</p></div><div class="opportunity-badge-row">${opportunityTierBadge(item.screening_tier)}${opportunityCurrencyBadge(item.screening_currency_status)}</div><dl><div><dt>Rent position</dt><dd>${escapeHTML(formatGap(current?item.rent_gap_pct:null,'market'))}</dd></div><div><dt>Basis</dt><dd>${formatOpportunityMoney(item.acquisition_basis,item.basis_unit,true)}</dd></div><div><dt>Evidence</dt><dd>${escapeHTML(formatOpportunityPercent(current?item.evidence_completeness:null))}</dd></div><div><dt>Freshness</dt><dd>${current&&item.evidence_freshness_days!==null?`${escapeHTML(item.evidence_freshness_days)} days`:'—'}</dd></div></dl><button class="secondary opportunity-open" data-id="${escapeHTML(item.id)}" type="button">Open evidence →</button></article>`;
}
function renderOpportunityFinder(){
  const finder=opportunityState();renderOpportunitySummary();const writable=canManageOpportunities();$('#opportunity-add-candidate').hidden=!writable;
  const target=$('#opportunity-list');
  if(!finder.items.length){const filtered=Object.entries(finder.filters).some(([key,value])=>value&&![['status','candidate'],['sort','screening_tier'],['direction','asc']].some(([defaultKey,defaultValue])=>key===defaultKey&&value===defaultValue));target.innerHTML=`<div class="empty-state"><span>⌕</span><h2>${filtered?'No candidates match these filters.':'No opportunity candidates yet.'}</h2><p>${filtered?'Adjust or clear the current evidence filters.':'Create a candidate manually or add authorized property evidence.'}</p>${writable?'<button class="primary opportunity-empty-add" type="button">+ Add candidate</button>':''}</div>`}
  else target.innerHTML=`<div class="opportunity-table table-wrap"><table class="data-table"><thead><tr><th>Property</th><th>Market</th><th>Type</th><th>Basis</th><th>Rent gap</th><th>Evidence-supported NOI delta</th><th>Evidence</th><th>Freshness</th><th>Tier</th><th>Screening state</th><th><span class="sr-status">Actions</span></th></tr></thead><tbody>${finder.items.map(opportunityRow).join('')}</tbody></table></div><div class="opportunity-cards">${finder.items.map(opportunityCard).join('')}</div>`;
  const first=finder.total?finder.page*finder.limit+1:0,last=Math.min((finder.page+1)*finder.limit,finder.total),pages=Math.max(1,Math.ceil(finder.total/finder.limit));$('#opportunity-page-label').textContent=`${first}–${last} of ${finder.total} · page ${finder.page+1} of ${pages}`;$('#opportunity-previous').disabled=finder.page===0;$('#opportunity-next').disabled=last>=finder.total;$('#opportunity-list-status').textContent=`Showing ${first} through ${last} of ${finder.total} authorized candidates`;
  document.querySelectorAll('.opportunity-open').forEach(button=>button.addEventListener('click',()=>openOpportunityDetail(button.dataset.id)));
  document.querySelector('.opportunity-empty-add')?.addEventListener('click',openOpportunityCandidateDialog);
}
function detailMetric(label,value,note=''){return`<article><span>${escapeHTML(label)}</span><strong>${value}</strong><small>${escapeHTML(note)}</small></article>`}
function opportunityEvidenceHealth(inputs,result){
  const ages=result?.evidenceFreshnessDetail?.evidenceAgeByDimension||{},hashes=inputs.evidence_hashes||{},dates=inputs.evidence_dates||{};
  return OPPORTUNITY_DIMENSIONS.map(dimension=>{const hasHashes=(hashes[dimension]||[]).length>0,hasDate=Boolean(dates[dimension]),age=ages[dimension];let status='Missing';if(hasHashes&&hasDate)status=age>365?'Stale':'Available';else if(hasHashes)status='Missing date';else if(hasDate)status='Missing provenance';return`<tr><td>${escapeHTML(dimension.replaceAll('_',' '))}</td><td>${escapeHTML(status)}</td><td>${escapeHTML(dates[dimension]||'—')}</td><td>${age===null||age===undefined?'—':`${escapeHTML(age)} days`}</td><td>${escapeHTML((hashes[dimension]||[]).length)}</td></tr>`}).join('');
}
function renderOpportunityDetail(detail,history){
  const c=detail.candidate,version=detail.versions.at(-1),inputs=version?.content?.inputs||{},run=detail.latest_screening||detail.current_screening,result=run?.result||{},historicProjection=detail.screening_projection||{},screeningCurrent=detail.screening_currency_status==='CURRENT',projection=screeningCurrent?historicProjection:{screening_tier:historicProjection.screening_tier},writable=canManageOpportunities()&&c.status==='candidate';
  const reasons=result.reasons||[],warnings=result.warnings||[];
  const reasonCards=reasons.length?reasons.map(reason=>`<article class="opportunity-reason"><span>${escapeHTML(reason.dimension.replaceAll('_',' '))}</span><h3>${escapeHTML(reason.statement)}</h3><p>Observed signal: <strong>${escapeHTML(reason.value??'—')}</strong> · policy threshold: ${escapeHTML(reason.threshold??'—')}</p><p>${escapeHTML((reason.evidence_hashes||[]).length)} source hash(es) contributed</p></article>`).join(''):'<p class="empty">No affirmative screening reasons. Missing evidence remains missing.</p>';
  const warningCards=warnings.length?warnings.map(warning=>`<li><strong>${escapeHTML(warning.code.replaceAll('_',' '))}</strong><br>${escapeHTML(warning.statement)}</li>`).join(''):'<li>No screening warnings were recorded for the latest run.</li>';
  const basis=formatOpportunityMoney(inputs.acquisition_basis,inputs.basis_unit,true),comparableBasis=formatOpportunityMoney(inputs.comparable_sale_basis,inputs.basis_unit,true),rentUnit=inputs.rent_unit||'';
  const versionHistory=detail.versions.length?detail.versions.slice().reverse().map(item=>`<details><summary>Evidence v${escapeHTML(item.version)} · ${escapeHTML(item.analysis_as_of)} · ${escapeHTML(item.content_sha256.slice(0,16))}…</summary><p>Created ${escapeHTML(item.created_at)} by ${escapeHTML(item.created_by)}. Immutable schema ${escapeHTML(item.schema_version)}.</p><pre>${escapeHTML(JSON.stringify(item.content.inputs,null,2))}</pre></details>`).join(''):'<p class="empty">No evidence versions.</p>';
  const versionsById=new Map(detail.versions.map(item=>[item.id,item.version])),unscreenedEvent=detail.screening_currency_status==='OUTDATED_EVIDENCE'&&version?`<article class="history-row"><div>${opportunityCurrencyBadge('NOT_SCREENED')}<strong>Evidence v${escapeHTML(version.version)}</strong></div><p>Evidence added ${escapeHTML(version.created_at)} · screening pending</p></article>`:'';
  const runHistory=detail.screening_runs.length?unscreenedEvent+detail.screening_runs.slice().reverse().map(item=>`<article class="history-row"><div>${opportunityTierBadge(item.screening_tier)}<strong>Evidence v${escapeHTML(versionsById.get(item.candidate_version_id)??'—')}</strong></div><p>Screened ${escapeHTML(item.evaluated_at)} · result ${escapeHTML(item.result_sha256.slice(0,16))}…</p></article>`).join(''):'<p class="empty">No immutable screening runs.</p>';
  $('#opportunity-detail').innerHTML=`<div class="page-head opportunity-detail-head"><div><p class="eyebrow">${escapeHTML(c.property_type.replaceAll('_',' '))}</p><h1>${escapeHTML(c.display_name||c.address||'Unnamed candidate')}</h1><p>${escapeHTML(c.address||'Address not supplied')} · ${escapeHTML([c.market,c.submarket].filter(Boolean).join(' / ')||'Market not supplied')}</p><div class="opportunity-badge-row">${opportunityTierBadge(projection.screening_tier)}${opportunityCurrencyBadge(detail.screening_currency_status)}<span class="opportunity-badge">${escapeHTML(c.status)}</span></div></div><div class="detail-actions">${writable?'<button id="opportunity-add-evidence" class="secondary" type="button">Add evidence</button>':''}${writable&&version?`<button id="opportunity-run-screen" class="primary" type="button">${detail.screening_currency_status==='OUTDATED_EVIDENCE'?'Rescreen latest evidence':'Run screening'}</button>`:''}${writable?'<button id="opportunity-archive" class="secondary danger-action" type="button">Archive</button>':''}</div></div>
  ${detail.screening_currency_status==='OUTDATED_EVIDENCE'?'<div class="notice"><strong>New evidence has not been screened.</strong> The displayed run is historic and must not be treated as current.</div>':''}
  <section class="opportunity-section"><div class="panel-head"><h2>Why this surfaced</h2><span class="badge">Deterministic evidence rules</span></div><div class="opportunity-reasons">${reasonCards}</div></section>
  <section class="opportunity-section opportunity-warning" aria-labelledby="opportunity-warning-title"><h2 id="opportunity-warning-title">Risks and warnings</h2><ul>${warningCards}</ul></section>
  <section class="opportunity-section"><div class="panel-head"><h2>Key metrics</h2><span class="badge">Missing values shown as —</span></div><div class="metrics opportunity-detail-metrics">${detailMetric('Subject rent',inputs.subject_rent?`${escapeHTML(inputs.subject_rent)} ${escapeHTML(rentUnit)}`:'—')}${detailMetric('Market rent',inputs.market_rent?`${escapeHTML(inputs.market_rent)} ${escapeHTML(rentUnit)}`:'—')}${detailMetric('Rent position',escapeHTML(formatGap(projection.rent_gap_pct,'market')))}${detailMetric('Acquisition basis',basis)}${detailMetric('Comparable basis',comparableBasis)}${detailMetric('Basis position',escapeHTML(formatGap(projection.basis_discount_pct,'comparables')))}${detailMetric('Current NOI',formatOpportunityMoney(inputs.current_noi,'USD'))}${detailMetric('Stabilized evidence NOI',formatOpportunityMoney(inputs.stabilized_noi,'USD'))}${detailMetric('Evidence-supported NOI delta',formatOpportunityMoney(projection.evidence_supported_noi_delta,'USD'),'Supplied evidence comparison; not an Underwrite forecast')}${detailMetric('Subject / market cap',`${formatOpportunityPercent(inputs.subject_cap_rate)} / ${formatOpportunityPercent(inputs.market_cap_rate)}`)}${detailMetric('Cap spread',projection.cap_rate_spread_bps===null||projection.cap_rate_spread_bps===undefined?'—':`${escapeHTML(projection.cap_rate_spread_bps)} bps`)}${detailMetric('Subject / market vacancy',`${formatOpportunityPercent(inputs.subject_vacancy)} / ${formatOpportunityPercent(inputs.market_vacancy)}`)}${detailMetric('Vacancy delta',escapeHTML(formatOpportunityPercent(projection.vacancy_delta)))}</div></section>
  <section class="opportunity-section"><div class="panel-head"><h2>Evidence health and provenance</h2><span class="badge">${escapeHTML(formatOpportunityPercent(projection.evidence_completeness))} complete</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Dimension</th><th>Status</th><th>Evidence date</th><th>Age</th><th>Source hashes</th></tr></thead><tbody>${opportunityEvidenceHealth(inputs,screeningCurrent?result:{})}</tbody></table></div><p class="evidence-note">Oldest evidence: ${escapeHTML(projection.oldest_evidence_age_days??'—')} days · newest evidence: ${escapeHTML(screeningCurrent?result.evidenceFreshnessDetail?.newestEvidenceAgeDays??'—':'—')} days · signal evidence maximum age: ${escapeHTML(projection.signal_evidence_max_age_days??'—')} days.</p></section>
  <section class="opportunity-section honest-score"><h2>Validated opportunity score</h2><strong>Not available</strong><p>Insufficient governed realized acquisition outcome data. Screening tiers do not substitute for a validated score.</p></section>
  <div class="opportunity-history-grid"><section class="opportunity-section"><div class="panel-head"><h2>Screening history</h2><span class="badge">Immutable</span></div>${runHistory}</section><section class="opportunity-section"><div class="panel-head"><h2>Evidence version history</h2><span class="badge">Immutable</span></div>${versionHistory}</section></div>
  <details class="opportunity-section"><summary>Lifecycle audit history</summary><pre>${escapeHTML(JSON.stringify(history.timeline,null,2))}</pre></details>`;
  $('#opportunity-add-evidence')?.addEventListener('click',openOpportunityEvidenceDialog);$('#opportunity-run-screen')?.addEventListener('click',runOpportunityScreening);$('#opportunity-archive')?.addEventListener('click',archiveOpportunity);
}
async function openOpportunityDetail(candidateId){
  const finder=opportunityState();finder.lastOpened=candidateId;$('#opportunity-finder-list-view').hidden=true;$('#opportunity-detail-view').hidden=false;$('#opportunity-detail').innerHTML='<p class="empty">Loading source-linked evidence…</p>';
  const [detail,history]=await Promise.all([api(`/api/opportunities/${encodeURIComponent(candidateId)}`),api(`/api/opportunities/${encodeURIComponent(candidateId)}/history`)]);finder.detail=detail;finder.history=history;renderOpportunityDetail(detail,history);syncOpportunityUrl(candidateId);$('#opportunity-back').focus();
}
function closeOpportunityDetail(){const finder=opportunityState();finder.detail=null;finder.history=null;$('#opportunity-detail-view').hidden=true;$('#opportunity-finder-list-view').hidden=false;syncOpportunityUrl();document.querySelector(`.opportunity-open[data-id="${CSS.escape(finder.lastOpened||'')}"]`)?.focus()}
function openOpportunityCandidateDialog(){opportunityDialogOpener=document.activeElement;$('#opportunity-candidate-form').reset();$('#opportunity-candidate-dialog').showModal();$('#opportunity-candidate-form select').focus()}
function openOpportunityEvidenceDialog(){opportunityDialogOpener=document.activeElement;const form=$('#opportunity-evidence-form');form.reset();form.elements.analysis_as_of.max=new Date().toISOString().slice(0,10);form.elements.analysis_as_of.value=opportunityState().detail?.latest_evidence_analysis_as_of||new Date().toISOString().slice(0,10);$('#opportunity-evidence-dialog').showModal();form.elements.analysis_as_of.focus()}
function evidencePayload(form){
  const data=new FormData(form),payload={analysis_as_of:data.get('analysis_as_of')},decimals=['subject_rent','market_rent','acquisition_basis','comparable_sale_basis','current_noi','stabilized_noi','subject_cap_rate','market_cap_rate','subject_vacancy','market_vacancy'],strings=['rent_unit','basis_unit','insurance_evidence_date'];
  decimals.forEach(field=>{const value=String(data.get(field)||'').trim();if(value)payload[field]=value});strings.forEach(field=>{const value=String(data.get(field)||'').trim();if(value)payload[field]=value});['rent_comp_count','sale_comp_count'].forEach(field=>{const value=String(data.get(field)||'').trim();if(value)payload[field]=Number(value)});['location_evidence_complete','renovation_budget_verified'].forEach(field=>{if(data.get(field)==='on')payload[field]=true});payload.evidence_hashes={};payload.evidence_dates={};
  OPPORTUNITY_DIMENSIONS.forEach(dimension=>{const hashText=String(data.get(`hash_${dimension}`)||'').trim(),observed=String(data.get(`date_${dimension}`)||'').trim();if(hashText){const hashes=[...new Set(hashText.split(/[\s,]+/).filter(Boolean).map(value=>value.toLowerCase()))];if(hashes.some(value=>!/^[0-9a-f]{64}$/.test(value)))throw new Error(`${dimension.replaceAll('_',' ')} evidence contains an invalid SHA-256`);payload.evidence_hashes[dimension]=hashes}if(observed)payload.evidence_dates[dimension]=observed});return payload;
}
async function runOpportunityScreening(){const finder=opportunityState(),button=$('#opportunity-run-screen');button.disabled=true;try{await api(`/api/opportunities/${encodeURIComponent(finder.detail.candidate.id)}/screen`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});toast('Server-side screening completed');await openOpportunityDetail(finder.detail.candidate.id);await loadOpportunityFinder(true)}finally{button.disabled=false}}
async function archiveOpportunity(){const finder=opportunityState();if(!confirm('Archive this candidate? Evidence and screening history will remain immutable and available.'))return;await api(`/api/opportunities/${encodeURIComponent(finder.detail.candidate.id)}/archive`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});toast('Candidate archived; evidence history retained');closeOpportunityDetail();await loadOpportunityFinder(true)}

$('#opportunity-back').addEventListener('click',closeOpportunityDetail);
$('#opportunity-add-candidate').addEventListener('click',openOpportunityCandidateDialog);
$('#opportunity-previous').addEventListener('click',()=>{const finder=opportunityState();if(finder.page>0){finder.page--;loadOpportunityFinder(true)}});
$('#opportunity-next').addEventListener('click',()=>{const finder=opportunityState();if((finder.page+1)*finder.limit<finder.total){finder.page++;loadOpportunityFinder(true)}});
$('#opportunity-page-size').addEventListener('change',event=>{const finder=opportunityState();finder.limit=Number(event.target.value);finder.page=0;loadOpportunityFinder(true)});
$('#opportunity-clear-filters').addEventListener('click',()=>{const form=$('#opportunity-filters');form.reset();const finder=opportunityState();finder.filters={status:'candidate',sort:'screening_tier',direction:'asc'};finder.page=0;loadOpportunityFinder(true)});
$('#opportunity-filters').addEventListener('input',event=>{clearTimeout(opportunitySearchTimer);opportunitySearchTimer=setTimeout(()=>{const finder=opportunityState(),data=new FormData(event.currentTarget),sort=String(data.get('sort')||'screening_tier');finder.filters={status:'candidate',sort,direction:sort==='screening_tier'?'asc':'desc'};for(const [key,value]of data.entries())if(String(value).trim())finder.filters[key]=String(value).trim();finder.page=0;loadOpportunityFinder(true)},event.target.type==='search'?280:0)});
$('#opportunity-candidate-form').addEventListener('submit',async event=>{event.preventDefault();if(event.submitter?.value==='cancel'){$('#opportunity-candidate-dialog').close();return}const form=event.currentTarget;if(!form.reportValidity())return;const payload=Object.fromEntries([...new FormData(form)].filter(([,value])=>String(value).trim()));if(!payload.display_name&&!payload.address){toast('Display name or address is required');return}const button=$('#opportunity-create-candidate');button.disabled=true;try{const created=await api('/api/opportunities',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#opportunity-candidate-dialog').close();toast(created.warnings?.length?'Candidate created with a possible duplicate warning':'Candidate created');await loadOpportunityFinder(true);await openOpportunityDetail(created.id)}catch(error){toast(error.message)}finally{button.disabled=false}});
$('#opportunity-evidence-form').addEventListener('submit',async event=>{event.preventDefault();if(event.submitter?.value==='cancel'){$('#opportunity-evidence-dialog').close();return}const form=event.currentTarget;if(!form.reportValidity())return;const button=$('#opportunity-create-evidence');button.disabled=true;try{const payload=evidencePayload(form),candidateId=opportunityState().detail.candidate.id;await api(`/api/opportunities/${encodeURIComponent(candidateId)}/versions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('#opportunity-evidence-dialog').close();toast('Immutable evidence version created');await openOpportunityDetail(candidateId);await loadOpportunityFinder(true)}catch(error){toast(error.message)}finally{button.disabled=false}});
for(const dialog of [$('#opportunity-candidate-dialog'),$('#opportunity-evidence-dialog')])dialog.addEventListener('close',()=>opportunityDialogOpener?.focus());
$('#opportunity-provenance-fields').innerHTML=OPPORTUNITY_DIMENSIONS.map(dimension=>`<label>${escapeHTML(dimension.replaceAll('_',' '))} source SHA-256<textarea name="hash_${escapeHTML(dimension)}" rows="2" maxlength="6600"></textarea></label><label>${escapeHTML(dimension.replaceAll('_',' '))} evidence date<input name="date_${escapeHTML(dimension)}" type="date"></label>`).join('');
